version: '3'
services:
  web:
    build: './web'
    ports:
      - '3000:3000'
    environment:
      - PORT=3000

  search:
    build: './search'
    ports:
      - '3001:3000'

  books:
    build: './books'
    ports:
      - '3002:3000'
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://db/microservices-demo

  todo:
    build: './todo'
    ports:
      - '3003:3000'
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://db/microservices-demo

  db:
    image: mongo:3.6
    ports:
      - '27017:27017'

  nginx:
    image: nginx:latest
    ports:
      - '8080:8080'
    volumes:
      - ./web/webapp/build:/server/www/static
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
      - books
      - todo
      - search
